version : '2.1'

services:
  db_auth:
    container_name: db_auth
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=superpassword
      - POSTGRES_USER=postgres
    image: postgis/postgis
